### ISSUE TITLE
Z00E

### ISSUE THREAD

**Issue by mgkirs** [zf2-laser-dev/TODO#1]
http://unlock-bootloader.net/how-to/unlock-bootloader-asus-zenfone-2-laser-ze500kl/
Do I understand correctly? Du you can now build and run cyanogenmod 13 on Z00E?

**Comment by luk1337** [comment]
This website is fake lol. Btw who said like I want to build anything for
Z00E?

**Comment by mgkirs** [comment]
i found cyanogenmod for ZOOL https://wiki.cyanogenmod.org/w/Z00L_Info, then clicked on github and find TODO for ZOOE
PS lol, I don't looked a link into the article
